# Generated by Django 3.2 on 2021-04-25 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='uploadfile',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='enrollment',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
