# Generated by Django 3.2 on 2021-04-29 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210425_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='qsfile',
            field=models.FileField(default=None, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])]),
        ),
    ]
